version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes: [redis_data:/data]
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  redis-cluster:
    image: redis:7-alpine
    ports: ["6380:6379"]
    volumes: [redis_cluster_data:/data]
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    restart: unless-stopped

  backend-1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports: ["3001:3001"]
    depends_on: [redis]
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=1
      - MAX_CONNECTIONS=1000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backend-2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports: ["3002:3001"]
    depends_on: [redis]
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=2
      - MAX_CONNECTIONS=1000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backend-3:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports: ["3003:3001"]
    depends_on: [redis]
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=3
      - MAX_CONNECTIONS=1000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [backend-1, backend-2, backend-3]
    restart: unless-stopped

  frontend:
    build:
      context: ./chat-dashboard
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    depends_on: [nginx]
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
    restart: unless-stopped

volumes:
  redis_data:
  redis_cluster_data:
